### ISSUE TITLE
Shery.js library is now working 

### ISSUE THREAD

**Issue by ChanakaRajapaksha** [sheryislive/Cuberto#5]

**Comment by VivekSaha05** [comment]
same problem em facing too. Only the normal html and css is rendering. the shery.js isnt working at all

**Comment by Sunit46x** [comment]
same issue library is not working

**Comment by git-maniesh** [comment]
use this in the script tag at the bottom of the body tag    and make sure when you use the shery js the first letter to be capitalized use the below code to check your code is runing or not 

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/0.155.0/three.min.js"></script>


<script src="https://cdn.jsdelivr.net/gh/automat/controlkit.js@master/bin/controlKit.min.js"></script>

**Comment by git-maniesh** [comment]
use this in the script tag at the bottom of the body tag and make sure when you use the shery js the first letter to be capitalized use the below code to check your code is running or not
//add the below code in script js file 
Shery.mouseFollower({ 
//Parameters are optional. 
skew: true, 
ease: "cubic-bezier(0.23, 1, 0.320, 1)", 
duration: 1, 
}); 
<script type="text/javascript" src="https://unpkg.com/sheryjs/dist/Shery.js"></script> 
//these below libraries are also required add them before script js file

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/0.155.0/three.min.js"></script> 
<script src="https://cdn.jsdelivr.net/gh/automat/controlkit.js@master/bin/controlKit.min.js"></script>

**Comment by CodeRunner001** [comment]
same problem Shery js isn't working

**Comment by Ayushnegi1234567** [comment]
Shery.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'PlaneGeometry')
    at Module.Cr (Shery.js:2:90835)
    at script.js:24:7

**Comment by PratikshyaDas2004** [comment]
it is not working.

**Comment by utkarshahu** [comment]
shery js working properly its very good
